package com.google.android.gms.internal;

import com.google.android.gms.common.api.C1263g;
import com.google.android.gms.common.api.C1279d;
import com.google.android.gms.common.api.C1279d.C1278a;
import com.google.android.gms.common.api.C1282h;
import com.google.android.gms.common.api.Status;

public class ae<R extends C1263g> extends C1279d<R> {
    private final Status f3279a;

    public Integer m5043a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void m5044a(C1278a c1278a) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void m5045a(C1282h<? super R> c1282h) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    Status m5046b() {
        return this.f3279a;
    }
}
