package com.google.android.gms.internal;

import android.content.Context;
import android.support.v7.recyclerview.BuildConfig;
import com.google.android.gms.ads.internal.zzv;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;

@op
/* renamed from: com.google.android.gms.internal.if */
public final class C1648if {
    public static final ib<Long> f4337A;
    public static final ib<Boolean> f4338B;
    public static final ib<Long> f4339C;
    public static final ib<Boolean> f4340D;
    public static final ib<Integer> f4341E;
    public static final ib<Long> f4342F;
    public static final ib<Boolean> f4343G;
    public static final ib<Boolean> f4344H;
    public static final ib<String> f4345I;
    public static final ib<Boolean> f4346J;
    public static final ib<Boolean> f4347K;
    public static final ib<Float> f4348L;
    public static final ib<String> f4349M;
    public static final ib<String> f4350N;
    public static final ib<Boolean> f4351O;
    public static final ib<Boolean> f4352P;
    public static final ib<Boolean> f4353Q;
    public static final ib<String> f4354R;
    public static final ib<String> f4355S;
    public static final ib<String> f4356T;
    public static final ib<Boolean> f4357U;
    public static final ib<String> f4358V;
    public static final ib<Boolean> f4359W;
    public static final ib<Boolean> f4360X;
    public static final ib<Boolean> f4361Y;
    public static final ib<Integer> f4362Z;
    public static final ib<String> f4363a;
    public static final ib<String> aA;
    public static final ib<String> aB;
    public static final ib<Long> aC;
    public static final ib<Boolean> aD;
    public static final ib<Long> aE;
    public static final ib<Long> aF;
    public static final ib<Boolean> aG;
    public static final ib<String> aH;
    public static final ib<Boolean> aI;
    public static final ib<Long> aJ;
    public static final ib<Boolean> aK;
    public static final ib<Boolean> aL;
    public static final ib<String> aM;
    public static final ib<String> aN;
    public static final ib<Integer> aO;
    public static final ib<Integer> aP;
    public static final ib<Integer> aQ;
    public static final ib<String> aR;
    public static final ib<String> aS;
    public static final ib<String> aT;
    public static final ib<String> aU;
    public static final ib<Boolean> aV;
    public static final ib<Boolean> aW;
    public static final ib<String> aX;
    public static final ib<Long> aY;
    public static final ib<Boolean> aZ;
    public static final ib<Integer> aa;
    public static final ib<Integer> ab;
    public static final ib<Integer> ac;
    public static final ib<Integer> ad;
    public static final ib<Boolean> ae;
    public static final ib<Integer> af;
    public static final ib<Boolean> ag;
    public static final ib<Integer> ah;
    public static final ib<Integer> ai;
    public static final ib<String> aj;
    public static final ib<String> ak;
    public static final ib<Boolean> al;
    public static final ib<Boolean> am;
    public static final ib<Long> an;
    public static final ib<String> ao;
    public static final ib<String> ap;
    public static final ib<Boolean> aq;
    public static final ib<Boolean> ar;
    public static final ib<Boolean> as;
    public static final ib<String> at;
    public static final ib<Boolean> au;
    public static final ib<Boolean> av;
    public static final ib<Integer> aw;
    public static final ib<Boolean> ax;
    public static final ib<String> ay;
    public static final ib<Boolean> az;
    public static final ib<String> f4364b;
    public static final ib<Boolean> bA;
    public static final ib<String> bB;
    public static final ib<Boolean> bC;
    public static final ib<String> bD;
    public static final ib<Boolean> bE;
    public static final ib<String> bF;
    public static ib<Boolean> bG;
    public static ib<String> bH;
    public static final ib<String> bI;
    public static final ib<Boolean> bJ;
    public static final ib<Boolean> bK;
    public static final ib<Boolean> bL;
    public static final ib<Boolean> bM;
    public static final ib<Boolean> bN;
    public static final ib<String> bO;
    public static final ib<Boolean> bP;
    public static final ib<Boolean> bQ;
    public static final ib<Boolean> bR;
    public static final ib<Boolean> bS;
    public static final ib<Boolean> bT;
    public static final ib<Boolean> bU;
    public static final ib<String> bV;
    public static final ib<String> bW;
    public static final ib<String> bX;
    public static final ib<Long> bY;
    public static final ib<Boolean> bZ;
    public static final ib<Long> ba;
    public static final ib<Boolean> bb;
    public static final ib<Boolean> bc;
    public static final ib<Boolean> bd;
    public static final ib<Boolean> be;
    public static final ib<Boolean> bf;
    public static final ib<Boolean> bg;
    public static final ib<Boolean> bh;
    public static final ib<Boolean> bi;
    public static final ib<String> bj;
    public static final ib<Long> bk;
    public static final ib<Boolean> bl;
    public static final ib<Boolean> bm;
    public static final ib<Long> bn;
    public static final ib<Long> bo;
    public static final ib<Boolean> bp;
    public static final ib<Long> bq;
    public static final ib<String> br;
    public static final ib<Boolean> bs;
    public static final ib<String> bt;
    public static final ib<Boolean> bu;
    public static final ib<Boolean> bv;
    public static final ib<String> bw;
    public static final ib<Boolean> bx;
    public static final ib<String> by;
    public static final ib<Boolean> bz;
    public static final ib<Boolean> f4365c;
    public static final ib<String> cA;
    public static final ib<Long> cB;
    public static final ib<String> cC;
    public static final ib<String> cD;
    public static final ib<String> cE;
    public static final ib<String> cF;
    public static final ib<String> cG;
    public static final ib<String> cH;
    public static final ib<String> cI;
    public static final ib<Long> cJ;
    public static final ib<Boolean> cK;
    public static final ib<Boolean> cL;
    public static final ib<Boolean> cM;
    public static final ib<Long> cN;
    public static final ib<String> cO;
    public static final ib<Long> cP;
    public static final ib<Boolean> cQ;
    public static final ib<Boolean> cR;
    public static final ib<Integer> cS;
    public static final ib<Long> cT;
    public static final ib<Boolean> cU;
    public static final ib<Boolean> cV;
    public static final ib<Boolean> cW;
    public static final ib<Long> cX;
    public static final ib<Boolean> cY;
    public static final ib<Boolean> cZ;
    public static final ib<Boolean> ca;
    public static final ib<String> cb;
    public static final ib<String> cc;
    public static final ib<Boolean> cd;
    public static final ib<String> ce;
    public static final ib<Boolean> cf;
    public static final ib<Boolean> cg;
    public static final ib<Boolean> ch;
    public static final ib<Integer> ci;
    public static final ib<String> cj;
    public static final ib<String> ck;
    public static final ib<Boolean> cl;
    public static final ib<Boolean> cm;
    public static final ib<Boolean> cn;
    public static final ib<Boolean> co;
    public static final ib<Boolean> cp;
    public static final ib<Long> cq;
    public static final ib<Integer> cr;
    public static final ib<Integer> cs;
    public static final ib<Boolean> ct;
    public static final ib<String> cu;
    public static final ib<Long> cv;
    public static final ib<String> cw;
    public static final ib<Long> cx;
    public static final ib<String> cy;
    public static final ib<Boolean> cz;
    public static final ib<String> f4366d;
    public static final ib<Boolean> da;
    public static final ib<Boolean> db;
    public static final ib<String> dc;
    public static final ib<String> dd;
    public static final ib<String> de;
    public static final ib<String> df;
    public static final ib<Integer> dg;
    public static final ib<Integer> dh;
    public static final ib<Boolean> di;
    public static final ib<Boolean> dj;
    public static final ib<Boolean> f4367e;
    public static final ib<String> f4368f;
    public static final ib<Boolean> f4369g;
    public static final ib<Boolean> f4370h;
    public static final ib<String> f4371i;
    public static final ib<Boolean> f4372j;
    public static final ib<String> f4373k;
    public static final ib<String> f4374l;
    public static final ib<String> f4375m;
    public static final ib<Boolean> f4376n;
    public static final ib<Integer> f4377o;
    public static final ib<String> f4378p;
    public static final ib<String> f4379q;
    public static final ib<Integer> f4380r;
    public static final ib<Integer> f4381s;
    public static final ib<Integer> f4382t;
    public static final ib<Integer> f4383u;
    public static final ib<Long> f4384v;
    public static final ib<Long> f4385w;
    public static final ib<Integer> f4386x;
    public static final ib<Boolean> f4387y;
    public static final ib<String> f4388z;

    /* renamed from: com.google.android.gms.internal.if.1 */
    class C16471 implements Callable<Void> {
        final /* synthetic */ Context f4336a;

        C16471(Context context) {
            this.f4336a = context;
        }

        public Void m6702a() {
            zzv.zzcV().m6701a(this.f4336a);
            return null;
        }

        public /* synthetic */ Object call() {
            return m6702a();
        }
    }

    static {
        f4363a = ib.m6672a(0, "gads:sdk_core_experiment_id");
        f4364b = ib.m6677a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
        f4365c = ib.m6676a(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
        f4366d = ib.m6672a(0, "gads:request_builder:singleton_webview_experiment_id");
        f4367e = ib.m6676a(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
        f4368f = ib.m6672a(0, "gads:sdk_use_dynamic_module_experiment_id");
        f4369g = ib.m6676a(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
        f4370h = ib.m6676a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
        f4371i = ib.m6677a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
        f4372j = ib.m6676a(0, "gads:block_autoclicks", Boolean.valueOf(false));
        f4373k = ib.m6672a(0, "gads:block_autoclicks_experiment_id");
        f4374l = ib.m6678b(0, "gads:prefetch:experiment_id");
        f4375m = ib.m6672a(0, "gads:spam_app_context:experiment_id");
        f4376n = ib.m6676a(1, "gads:spam_app_context:enabled", Boolean.valueOf(false));
        f4377o = ib.m6674a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
        f4378p = ib.m6677a(1, "gads:video_exo_player:version", "1");
        f4379q = ib.m6672a(0, "gads:video_stream_cache:experiment_id");
        f4380r = ib.m6674a(1, "gads:video_stream_cache:limit_count", 5);
        f4381s = ib.m6674a(1, "gads:video_stream_cache:limit_space", 8388608);
        f4382t = ib.m6674a(1, "gads:video_stream_exo_allocator:segment_size", 65536);
        f4383u = ib.m6674a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
        f4384v = ib.m6675a(1, "gads:video_stream_cache:limit_time_sec", 300);
        f4385w = ib.m6675a(1, "gads:video_stream_cache:notify_interval_millis", 1000);
        f4386x = ib.m6674a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
        f4387y = ib.m6676a(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
        f4388z = ib.m6677a(1, "gads:video:metric_frame_hash_times", BuildConfig.VERSION_NAME);
        f4337A = ib.m6675a(1, "gads:video:metric_frame_hash_time_leniency", 500);
        f4338B = ib.m6676a(1, "gads:video:force_watermark", Boolean.valueOf(false));
        f4339C = ib.m6675a(1, "gads:video:surface_update_min_spacing_ms", 1000);
        f4340D = ib.m6676a(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
        f4341E = ib.m6674a(1, "gads:video:spinner:scale", 4);
        f4342F = ib.m6675a(1, "gads:video:spinner:jank_threshold_ms", 50);
        f4343G = ib.m6676a(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
        f4344H = ib.m6676a(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
        f4345I = ib.m6678b(0, "gads:spam_ad_id_decorator:experiment_id");
        f4346J = ib.m6676a(0, "gads:spam_ad_id_decorator:enabled", Boolean.valueOf(false));
        f4347K = ib.m6676a(0, "gads:ad_id_app_context:enabled", Boolean.valueOf(false));
        f4348L = ib.m6673a(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
        f4349M = ib.m6672a(0, "gads:ad_id_app_context:experiment_id");
        f4350N = ib.m6678b(0, "gads:looper_for_gms_client:experiment_id");
        f4351O = ib.m6676a(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
        f4352P = ib.m6676a(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
        f4353Q = ib.m6676a(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
        f4354R = ib.m6677a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
        f4355S = ib.m6677a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
        f4356T = ib.m6677a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
        f4357U = ib.m6676a(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
        f4358V = ib.m6677a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
        f4359W = ib.m6676a(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
        f4360X = ib.m6676a(1, "gads:use_adx_javascript_adapter", Boolean.valueOf(false));
        f4361Y = ib.m6676a(0, "gads:enable_content_fetching", Boolean.valueOf(true));
        f4362Z = ib.m6674a(0, "gads:content_length_weight", 1);
        aa = ib.m6674a(0, "gads:content_age_weight", 1);
        ab = ib.m6674a(0, "gads:min_content_len", 11);
        ac = ib.m6674a(0, "gads:fingerprint_number", 10);
        ad = ib.m6674a(0, "gads:sleep_sec", 10);
        ae = ib.m6676a(1, "gads:enable_content_url_hash", Boolean.valueOf(true));
        af = ib.m6674a(1, "gads:content_vertical_fingerprint_number", 100);
        ag = ib.m6676a(1, "gads:enable_content_vertical_hash", Boolean.valueOf(true));
        ah = ib.m6674a(1, "gads:content_vertical_fingerprint_bits", 23);
        ai = ib.m6674a(1, "gads:content_vertical_fingerprint_ngram", 3);
        aj = ib.m6677a(1, "gads:content_fetch_view_tag_id", "googlebot");
        ak = ib.m6677a(1, "gads:content_fetch_exclude_view_tag", "none");
        al = ib.m6676a(0, "gad:app_index_enabled", Boolean.valueOf(true));
        am = ib.m6676a(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
        an = ib.m6675a(0, "gads:app_index:timeout_ms", 1000);
        ao = ib.m6672a(0, "gads:app_index:experiment_id");
        ap = ib.m6672a(0, "gads:kitkat_interstitial_workaround:experiment_id");
        aq = ib.m6676a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
        ar = ib.m6676a(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
        as = ib.m6676a(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
        at = ib.m6672a(0, "gads:interstitial_follow_url:experiment_id");
        au = ib.m6676a(0, "gads:analytics_enabled", Boolean.valueOf(true));
        av = ib.m6676a(0, "gads:ad_key_enabled", Boolean.valueOf(false));
        aw = ib.m6674a(0, "gads:webview_cache_version", 0);
        ax = ib.m6676a(1, "gads:webview_recycle:enabled", Boolean.valueOf(false));
        ay = ib.m6672a(1, "gads:webview_recycle:experiment_id");
        az = ib.m6676a(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
        aA = ib.m6678b(0, "gads:pan:experiment_id");
        aB = ib.m6672a(1, "gads:rewarded:experiment_id");
        aC = ib.m6675a(1, "gads:rewarded:adapter_timeout_ms", 20000);
        aD = ib.m6676a(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
        aE = ib.m6675a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
        aF = ib.m6675a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
        aG = ib.m6676a(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
        aH = ib.m6672a(1, "gads:ad_manager_enforce_arp_invariant:experiment_id");
        aI = ib.m6676a(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(false));
        aJ = ib.m6675a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
        aK = ib.m6676a(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
        aL = ib.m6676a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
        aM = ib.m6677a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
        aN = ib.m6677a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
        aO = ib.m6674a(1, "gads:interstitial_ad_pool:max_pools", 3);
        aP = ib.m6674a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
        aQ = ib.m6674a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
        aR = ib.m6677a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
        aS = ib.m6677a(1, "gads:spherical_video:vertex_shader", BuildConfig.VERSION_NAME);
        aT = ib.m6677a(1, "gads:spherical_video:fragment_shader", BuildConfig.VERSION_NAME);
        aU = ib.m6672a(1, "gads:spherical_video:experiment_id");
        aV = ib.m6676a(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
        aW = ib.m6676a(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
        aX = ib.m6672a(1, "gads:include_local_global_rectangles:experiment_id");
        aY = ib.m6675a(1, "gads:position_watcher:throttle_ms", 200);
        aZ = ib.m6676a(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
        ba = ib.m6675a(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
        bb = ib.m6676a(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
        bc = ib.m6676a(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
        bd = ib.m6676a(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
        be = ib.m6676a(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
        bf = ib.m6676a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
        bg = ib.m6676a(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
        bh = ib.m6676a(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
        bi = ib.m6676a(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
        bj = ib.m6672a(0, "gads:gmsg:video_meta:experiment_id");
        bk = ib.m6675a(0, "gads:network:cache_prediction_duration_s", 300);
        bl = ib.m6676a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
        bm = ib.m6676a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
        bn = ib.m6675a(0, "gads:ad_loader:timeout_ms", 60000);
        bo = ib.m6675a(0, "gads:rendering:timeout_ms", 60000);
        bp = ib.m6676a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
        bq = ib.m6675a(1, "gads:gestures:task_timeout", 2000);
        br = ib.m6672a(1, "gads:gestures:encrypt_size_limit:experiment_id");
        bs = ib.m6676a(1, "gads:gestures:encrypt_size_limit:enabled", Boolean.valueOf(false));
        bt = ib.m6672a(1, "gads:gestures:appid:experiment_id");
        bu = ib.m6676a(1, "gads:gestures:appid:enabled", Boolean.valueOf(false));
        bv = ib.m6676a(0, "gads:gestures:v6:enabled", Boolean.valueOf(false));
        bw = ib.m6672a(1, "gads:gestures:usb_query:experiment_id");
        bx = ib.m6676a(1, "gads:gestures:usb_query:enabled", Boolean.valueOf(false));
        by = ib.m6672a(1, "gads:gestures:usb_click:experiment_id");
        bz = ib.m6676a(1, "gads:gestures:usb_click:enabled", Boolean.valueOf(false));
        bA = ib.m6676a(1, "gads:gestures:touchinfo:enabled", Boolean.valueOf(false));
        bB = ib.m6672a(1, "gads:gestures:touchinfo:experiment_id");
        bC = ib.m6676a(1, "gads:gestures:clock_query:enabled", Boolean.valueOf(false));
        bD = ib.m6672a(1, "gads:gestures:clock_query:experiment_id");
        bE = ib.m6676a(1, "gads:gestures:clock_click:enabled", Boolean.valueOf(false));
        bF = ib.m6672a(1, "gads:gestures:clock_click:experiment_id");
        bG = ib.m6676a(1, "gads:gestures:btl_click:enabled", Boolean.valueOf(false));
        bH = ib.m6672a(1, "gads:gestures:btl_click:experiment_id");
        bI = ib.m6672a(1, "gads:gestures:click_stk:experiment_id");
        bJ = ib.m6676a(1, "gads:gestures:click_stk:enabled", Boolean.valueOf(true));
        bK = ib.m6676a(1, "gads:gestures:visibility:enabled", Boolean.valueOf(false));
        bL = ib.m6676a(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
        bM = ib.m6676a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
        bN = ib.m6676a(0, "gass:client:enabled", Boolean.valueOf(true));
        bO = ib.m6672a(0, "gass:client:experiment_id");
        bP = ib.m6676a(0, "gass:enabled", Boolean.valueOf(true));
        bQ = ib.m6676a(0, "gass:enable_int_signal", Boolean.valueOf(true));
        bR = ib.m6676a(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
        bS = ib.m6676a(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
        bT = ib.m6676a(0, "gads:support_screen_shot", Boolean.valueOf(true));
        bU = ib.m6676a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
        bV = ib.m6672a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
        bW = ib.m6672a(1, "gads:sdk_core_constants:experiment_id");
        bX = ib.m6677a(1, "gads:sdk_core_constants:caps", BuildConfig.VERSION_NAME);
        bY = ib.m6675a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
        bZ = ib.m6676a(0, "gads:js_flags:mf", Boolean.valueOf(false));
        ca = ib.m6676a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
        cb = ib.m6677a(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        cc = ib.m6677a(1, "gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
        cd = ib.m6676a(1, "gads:singleton_webview_native", Boolean.valueOf(false));
        ce = ib.m6672a(1, "gads:singleton_webview_native:experiment_id");
        cf = ib.m6676a(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
        cg = ib.m6676a(1, "gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
        ch = ib.m6676a(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
        ci = ib.m6674a(1, "gads:native_video_load_timeout", 10);
        cj = ib.m6672a(1, "gads:native_video_load_timeout:experiment_id");
        ck = ib.m6677a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
        cl = ib.m6676a(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
        cm = ib.m6676a(1, "gads:enable_tracking_for_native_ad_views", Boolean.valueOf(true));
        cn = ib.m6676a(1, "gads:use_new_json_for_native_view_tracking", Boolean.valueOf(true));
        co = ib.m6676a(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
        cp = ib.m6676a(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
        cq = ib.m6675a(0, "gads:method_tracing:duration_ms", 30000);
        cr = ib.m6674a(0, "gads:method_tracing:count", 5);
        cs = ib.m6674a(0, "gads:method_tracing:filesize", 134217728);
        ct = ib.m6676a(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
        cu = ib.m6678b(1, "gads:auto_location_for_coarse_permission:experiment_id");
        cv = ib.m6675a(1, "gads:auto_location_timeout", 2000);
        cw = ib.m6678b(1, "gads:auto_location_timeout:experiment_id");
        cx = ib.m6675a(1, "gads:auto_location_interval", -1);
        cy = ib.m6678b(1, "gads:auto_location_interval:experiment_id");
        cz = ib.m6676a(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
        cA = ib.m6672a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
        cB = ib.m6675a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
        cC = ib.m6672a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms:experiment_id");
        cD = ib.m6672a(0, "gads:afs:csa:experiment_id");
        cE = ib.m6677a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
        cF = ib.m6677a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
        cG = ib.m6677a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
        cH = ib.m6677a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
        cI = ib.m6677a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
        cJ = ib.m6675a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
        cK = ib.m6676a(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
        cL = ib.m6676a(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
        cM = ib.m6676a(1, "gads:parental_controls:cache_results", Boolean.valueOf(true));
        cN = ib.m6675a(1, "gads:parental_controls:timeout", 2000);
        cO = ib.m6677a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
        cP = ib.m6675a(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
        cQ = ib.m6676a(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
        cR = ib.m6676a(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
        cS = ib.m6674a(1, "gads:cache:max_concurrent_downloads", 10);
        cT = ib.m6675a(1, "gads:cache:javascript_timeout_millis", 5000);
        cU = ib.m6676a(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
        cV = ib.m6676a(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
        cW = ib.m6676a(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
        cX = ib.m6675a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
        cY = ib.m6676a(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
        cZ = ib.m6676a(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
        da = ib.m6676a(1, "gads:drx_in_app_preview:enabled", Boolean.valueOf(false));
        db = ib.m6676a(1, "gads:drx_debug_signals:enabled", Boolean.valueOf(false));
        dc = ib.m6677a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
        dd = ib.m6677a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
        de = ib.m6677a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
        df = ib.m6677a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
        dg = ib.m6674a(1, "gads:drx_debug:timeout_ms", 5000);
        dh = ib.m6674a(1, "gad:pixel_dp_comparision_multiplier", 1);
        di = ib.m6676a(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
        dj = ib.m6676a(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
    }

    public static List<String> m6703a() {
        return zzv.zzcU().m6693a();
    }

    public static void m6704a(Context context) {
        sd.m8680a(new C16471(context));
    }

    public static List<String> m6705b() {
        return zzv.zzcU().m6695b();
    }
}
